

site_name: Using Text as Data in Marketing Research @ Adelaide Business School

nav:
  - Home: index.md
  - Instructor: instructor.md
  - Software Installation: installation.md 
  - Course Material: course_material.md
  - Code of Conduct:
    - Social Rules: conduct/social_rules.md
    - Code of Conduct: conduct/conduct.md
  - License:
    - License: license/license.md
    - Citation: license/citation.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
